### ISSUE TITLE
Missing privilege check in the mknod, mount and umount syscalls

### ISSUE THREAD

**Issue by Myldero** [maestro-os/maestro#24]
According to [the man page](https://www.man7.org/linux/man-pages/man2/mknod.2.html), the `mknod` syscall should return `EPERM` when an unprivileged user requests anything except "a regular file, FIFO (named pipe), or UNIX domain socket".
The lack of this check means that an unprivileged user can create a new device node for any connected hard disks to read the entire contents:
```bash
mknod foo b 8 0
```

The mount and umount syscalls should also only be possible to run as a privileged user

**Comment by llenotre** [comment]
I rewrote `mknod`'s permissions check: https://github.com/maestro-os/maestro/pull/33/commits/4fbfe4bd0502226d0151ffd886220c8dc36a2fcf

The check is also present on [mount](https://github.com/maestro-os/maestro/blob/4fbfe4bd0502226d0151ffd886220c8dc36a2fcf/kernel/src/syscall/mount.rs#L47) and [umount](https://github.com/maestro-os/maestro/blob/4fbfe4bd0502226d0151ffd886220c8dc36a2fcf/kernel/src/syscall/umount.rs#L37).
