### ISSUE TITLE
MemSpace::map can overwrite kernel pages

### ISSUE THREAD

**Issue by Myldero** [maestro-os/maestro#25]
When run with `MAP_FIXED`, `MemSpace::map` has no limits to where a page is requested. Furthermore, it will always unmap any pre-existing page. This means that a user can hijack kernel pages (and thus execution) with `mmap` or the ELF parser.

**Comment by llenotre** [comment]
I seem to have [fixed it](https://github.com/maestro-os/maestro/blob/7ebcdebc8b170c591b803fb6adafe39bcb94b74f/kernel/src/process/mem_space/mod.rs#L103) in the past on the `cleanup` branch. Thus this issue will be closed when the PR is merged
