### ISSUE TITLE
Direction flag is not cleared when handling interrupts

### ISSUE THREAD

**Issue by Myldero** [maestro-os/maestro#26]
A user can set the direction flag and call an interrupt. Since the interrupt handler does not clear the direction flag, any subsequent string operations will thus have undefined behavior.

**Comment by llenotre** [comment]
Fixed by https://github.com/maestro-os/maestro/pull/17/commits/7ed7accf1812b3b6ec6a3b8b119deabdad6e348e. This issue will be closed when the PR is merged
