### ISSUE TITLE
How to load the prebuilt `maestro.iso.gz` with QEMU?

### ISSUE THREAD

**Issue by Marsman1996** [maestro-os/maestro#40]
Hi,

I tried to start maestro from source code but met some problems.
And I find there is a prebuilt `maestro.iso.gz` in the blog.
I tried to load it with QEMU with the command:
```
$ dd if=/dev/zero of=qemu_disk bs=1G count=1 status=progress
$ mkfs.ext2 ./qemu_disk
$ qemu-system-i386 -cdrom maestro.iso.gz -drive file=./qemu_disk,format=raw -device isa-debug-exit,iobase=0xf4,iosize=0x04 -nographic
```

And it could not read from CDROM.
Could you advise me on how to resolve this issue or point me to the relevant instructions?
The detailed log is:
```log
SeaBIOS (version 1.13.0-1ubuntu1.1)


iPXE (http://ipxe.org) 00:03.0 CA00 PCI2.10 PnP PMM+07F8CA10+07ECCA10 CA00
                                                                               


Booting from Hard Disk...
Boot failed: not a bootable disk

Booting from Floppy...
Boot failed: could not read the boot disk

Booting from DVD/CD...
Boot failed: Could not read from CDROM (code 0004)
Booting from ROM...
iPXE (PCI 00:03.0) starting execution...ok
iPXE initialising devices...ok



iPXE 1.0.0+git-20190109.133f4c4-0ubuntu3.2 -- Open Source Network Boot Firmware 
-- http://ipxe.org
Features: DNS HTTP HTTPS iSCSI NFS TFTP AoE ELF MBOOT PXE bzImage Menu PXEXT

net0: 52:54:00:12:34:56 using 82540em on 0000:00:03.0 (open)
  [Link:up, TX:0 TXE:0 RX:0 RXE:0]
Configuring (net0 52:54:00:12:34:56)...... ok
net0: 10.0.2.15/255.255.255.0 gw 10.0.2.2
net0: fec0::5054:ff:fe12:3456/64 gw fe80::2
net0: fe80::5054:ff:fe12:3456/64
Nothing to boot: No such file or directory (http://ipxe.org/2d03e13b)
No more network devices

No bootable device.
```

Thank you for any reply!

**Comment by llenotre** [comment]
Hello!

You probably want to try to unzip `maestro.iso.gz` before passing it to QEMU:

```
gzip -d maestro.iso.gz
```

**Comment by Marsman1996** [comment]
Thank you for your quick reply!

Now the QEMU could load the prebuilt ISO file successfully.

However, it now hangs in this stage:
```
Booting Maestro kernel version 0.1.0
Initializing time management...
Initializing devices management...
Initializing files management...
Initializing initramfs...
Initializing processes...
Hello world!
Booting system with maestro kernel, release 0.1.0
Initializing current TTY...
Mounting fstab filesystems...
Mounting `/tmp`...
Mounting `/proc`...
Loading default modules...
Loading module `/lib/modules/maestro-0.1.0/default/ps2.kmod`...
Loading module `ps2` version `0.1.0`
Test PS/2 controller...
Test PS/2 keyboard...
Enable PS/2 keyboard...
PS/2 keyboard ready
Launching services...
                                  .
                                .::.
                               :::::
                             .::::::.
                           .::::::::. Welcome to the Maestro installer!
                         .::::::::::.
                       .::::::::::::
                     ::::::::::::::
                  .:------::::::::.
                .--------------::
              :------=---------.
           .-===--=+=--------:
         .-======++==------:
        -======+*=======-.
       ======+*+======-.
      -====+*+======:
      ====*+=====-.
      ==+*====-.
      =++=-:.
     :=:.           .:-=+++++==--:::.. Press ENTER
    -.         .-*##*=-:
   :       :=*#*=.
    .:-=+**=:
```

And press ENTER does now change anything.

I'm using a ubuntu:24.04 docker container and QEMU 8.2.2.
The cmd is:
```bash
qemu-system-i386 -cdrom maestro.iso -drive file=./qemu_disk,format=raw -device isa-debug-exit,iobase=0xf4,iosize=0x04 -nographic -m 4G -accel kvm
```

**Comment by Marsman1996** [comment]
Can I use the latest kernel with this qemu_disk?

I tried to run `qemu-system-i386 -cdrom kernel.iso -drive file=./qemu_disk,format=raw -device isa-debug-exit,iobase=0xf4,iosize=0x04`, but it still loads the old kernel.

**Comment by llenotre** [comment]
This image dates back from the beginning of 2024, when the blogpost was published. I did not update it since.

You can still build it yourself though

**Comment by Marsman1996** [comment]
Hi, 

I can compile the kernel and generate a kernel.iso now. 
According to `kernel/README.md`, I need *A fully built operating system ... This system must be present on a raw disk in the file qemu_disk*
So I installed the prebuilt maestro.iso.gz in qemu_disk.

Now I should be able to load the newly compiled kernel.iso with the qemu_disk installed with the prebuilt maestro.iso.gz, according to the `kernel/README.md` and `kernel/scripts/qemu.sh`, am I right?

However, it still loads the old kernel...

Or can you provide a qemu_disk file which is able to loads Maestro kernel?

Thank you for any reply!

**Comment by llenotre** [comment]
Hi,

"A fully built operating system" is *not only* the kernel. An operating system is a kernel + the set of userspace programs that are working on it. This repository only allows to build the kernel. The full operating system is built by [maestro-install](https://github.com/maestro-os/maestro-install/)

You can however decide to build it yourself. To do so, `qemu_disk` must contain an *ext2* filesystem. Then you can mount it, and create your system into it (with the `/etc`, `/usr`, ... directories and all the usual content of an operating system).

At boot, the `/sbin/init` program will be run.

By the way, `cargo run` (with optionally `--release`) is a shorthand for running the kernel

**Comment by Marsman1996** [comment]
Thank you for your patient reply!
